name: Run Tests

# Определяем триггеры для запуска workflows
on:
  push:
    branches:
      - main  # Запускать тесты при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать тесты при создании pull request в ветку main

jobs:
  test:
    runs-on: ubuntu-latest  # Используем Ubuntu для выполнения тестов

    steps:
      - name: Checkout code  # Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Set up Python  # Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Версия Python (можете выбрать другую)

      - name: Install dependencies  # Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Предполагается, что у вас есть requirements.txt

      - name: Install Tesseract OCR  # Устанавливаем Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          sudo apt-get install -y libtesseract-dev
          sudo apt-get install -y libleptonica-dev

      - name: Run tests  # Запускаем тесты
        run: |
          python -m unittest discover -s . -p "*_test.py"  # Находим и запускаем все тесты